version: 2
jobs:
  build:
    docker:
      - image: circleci/node:stretch
      - image: circleci/mongo:xenial
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Tests
          command: yarn test


